[project]
name = "singapore-ev-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dagster==1.13.5",
    "dagster-dg-cli",
    "dagster-webserver",
    "dbt-bigquery",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["orchestrate*"]

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "orchestrate"
registry_modules = [
    "orchestrate.components.*",
]
